import React, { useCallback, useMemo, useRef, useState } from 'react';
import { Animated, FlatList, StyleSheet, TouchableOpacity, View, ViewToken, useWindowDimensions } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { BellOff, ChevronRight, Dices, EyeOff, Flame, Gift, Heart, Image as ImageIcon, Lock, Mic, Shield, UserPlus, Zap } from 'lucide-react-native';
import AppText from '@/components/AppText';
import WarmupLogo from '@/components/WarmupLogo';
import WarmupWordmark from '@/components/WarmupWordmark';

export type OnboardingMode = 'preview' | 'post-auth';
export type OnboardingFinishAction = 'get-started' | 'invite-partner';
interface Props { mode: OnboardingMode; onComplete: (action?: OnboardingFinishAction) => void; }
type Slide = { key:string; eyebrow:string; headline:string; subtext:string; Visual:React.ComponentType };
const ACCENT='#FF2E8A', ORANGE='#FF7A3D';

function Shell({children}:{children:React.ReactNode}){return <View style={styles.visualShell}><LinearGradient colors={['rgba(255,122,61,0.12)','rgba(255,46,138,0.08)','rgba(0,0,0,0)']} style={StyleSheet.absoluteFill}/>{children}</View>}
function VisualWelcome(){return <Shell><View style={styles.logoGlow}/><View style={styles.logoRing}><WarmupLogo size={92}/></View><View style={styles.wordmarkWrap}><WarmupWordmark size={18}/></View><View style={styles.twoPill}><Heart size={14} color={ACCENT} fill={ACCENT}/><AppText style={styles.twoPillText}>ONE PRIVATE SPACE · TWO PEOPLE</AppText></View></Shell>}
function VisualChat(){return <Shell><View style={styles.miniPhone}><View style={styles.miniHeader}><View style={styles.avatar}><Heart size={13} color="#fff" fill="#fff"/></View><View style={{flex:1}}><AppText style={styles.miniTitle}>Your person</AppText><AppText style={styles.miniTiny}>private chat</AppText></View><Lock size={14} color="rgba(255,255,255,.45)"/></View><View style={[styles.chatBubble,styles.chatLeft]}><AppText style={styles.chatText}>Thinking about you…</AppText></View><View style={[styles.chatBubble,styles.chatRight]}><AppText style={styles.chatText}>Good. You should be. 😉</AppText></View><View style={styles.mediaMessage}><View style={styles.blurTile}><EyeOff size={20} color="#fff"/><AppText style={styles.blurText}>Tap to reveal</AppText></View></View><View style={[styles.chatBubble,styles.chatLeft,styles.voiceBubble]}><Mic size={14} color={ORANGE}/><View style={styles.wave}>{[8,14,10,18,12,16,8].map((h,i)=><View key={i} style={[styles.waveBar,{height:h}]}/>)}</View><AppText style={styles.voiceTime}>0:08</AppText></View></View></Shell>}
function VisualVault(){return <Shell><View style={styles.vaultCard}><View style={styles.vaultHeader}><View><AppText style={styles.vaultTitle}>Vault</AppText><AppText style={styles.miniTiny}>just yours + your partner's</AppText></View><Lock size={18} color={ACCENT}/></View><View style={styles.grid}><LinearGradient colors={['#3A2028','#7A354F']} style={styles.gridTile}><ImageIcon size={22} color="rgba(255,255,255,.8)"/></LinearGradient><View style={[styles.gridTile,styles.gridBlur]}><EyeOff size={22} color="#fff"/><AppText style={styles.blurText}>Blurred</AppText></View><LinearGradient colors={['#2D233A','#6D3D75']} style={styles.gridTile}><ImageIcon size={22} color="rgba(255,255,255,.8)"/></LinearGradient><LinearGradient colors={['#39251F','#8B4B32']} style={styles.gridTile}><ImageIcon size={22} color="rgba(255,255,255,.8)"/></LinearGradient></View><View style={styles.featureStrip}><Shield size={14} color={ORANGE}/><AppText style={styles.featureStripText}>Not added to your camera roll</AppText></View></View></Shell>}
function VisualBurn(){const bars=Array.from({length:24});return <Shell><View style={styles.burnMedia}><ImageIcon size={30} color="rgba(255,255,255,.6)"/><View style={styles.burnBadge}><Flame size={13} color="#fff"/><AppText style={styles.burnBadgeText}>BURNING</AppText></View></View><View style={styles.timerWrap}><View style={styles.timerSegments}>{bars.map((_,i)=><View key={i} style={[styles.segment,{transform:[{rotate:`${i*15}deg`},{translateY:-46}],opacity:i<17?1:.16}]}/>)}</View><View style={styles.timerCenter}><AppText style={styles.timerText}>14:32</AppText><AppText style={styles.timerLabel}>LEFT</AppText></View></View><AppText style={styles.microCopy}>When the timer ends, it's gone.</AppText></Shell>}
function VisualPlay(){return <Shell><View style={styles.playStack}><View style={[styles.playCard,{transform:[{rotate:'-4deg'}]}]}><View style={styles.playIcon}><Dices size={22} color={ORANGE}/></View><View style={styles.playCopy}><AppText style={styles.playTitle}>Dice</AppText><AppText style={styles.playSub}>Let chance choose.</AppText></View><ChevronRight size={18} color="rgba(255,255,255,.3)"/></View><View style={[styles.playCard,styles.playHero]}><View style={[styles.playIcon,{backgroundColor:'rgba(255,46,138,.15)'}]}><Zap size={22} color={ACCENT}/></View><View style={styles.playCopy}><AppText style={styles.playTitle}>Dare</AppText><AppText style={styles.playSub}>Challenge your partner.</AppText></View><View style={styles.livePill}><AppText style={styles.livePillText}>LIVE</AppText></View></View><View style={[styles.playCard,{transform:[{rotate:'3deg'}]}]}><View style={styles.playIcon}><Gift size={22} color="#FF7AAE"/></View><View style={styles.playCopy}><AppText style={styles.playTitle}>Wish</AppText><AppText style={styles.playSub}>Drop a little hint.</AppText></View><ChevronRight size={18} color="rgba(255,255,255,.3)"/></View></View></Shell>}
function VisualStealth(){return <Shell><View style={styles.weatherCard}><View style={styles.weatherTop}><AppText style={styles.weatherCity}>Topeka</AppText><AppText style={styles.weatherTiny}>Mostly Clear</AppText></View><View style={styles.weatherMain}><AppText style={styles.weatherTemp}>72°</AppText><View style={styles.weatherSun}/></View><View style={styles.weatherLine}><AppText style={styles.weatherTiny}>H: 78°   L: 61°</AppText></View></View><View style={styles.stealthBadge}><EyeOff size={16} color={ACCENT}/><View style={{flex:1}}><AppText style={styles.stealthTitle}>Stealth Mode</AppText><AppText style={styles.stealthSub}>Warm Me Up can look like weather at a glance.</AppText></View></View><View style={styles.privacyRow}><BellOff size={14} color={ORANGE}/><AppText style={styles.privacyText}>Discreet notifications</AppText><View style={styles.dot}/><Shield size={14} color={ORANGE}/><AppText style={styles.privacyText}>Privacy controls</AppText></View></Shell>}
function VisualFinish(){return <Shell><View style={styles.finishHearts}><View style={[styles.personCircle,styles.personA]}><AppText style={styles.personInitial}>YOU</AppText></View><View style={styles.connection}><LinearGradient colors={[ORANGE,ACCENT]} start={{x:0,y:.5}} end={{x:1,y:.5}} style={styles.connectionLine}/><View style={styles.heartNode}><Heart size={22} color="#fff" fill="#fff"/></View></View><View style={[styles.personCircle,styles.personB]}><Heart size={28} color="#fff" fill="#fff"/></View></View><View style={styles.inviteCard}><UserPlus size={20} color={ACCENT}/><View style={{flex:1}}><AppText style={styles.inviteTitle}>One subscription. Both of you.</AppText><AppText style={styles.inviteSub}>Invite your partner and make the space yours.</AppText></View></View></Shell>}

const SLIDES:Slide[]=[
{key:'welcome',eyebrow:'WELCOME TO WARM ME UP',headline:'Just for two.',subtext:'A private app for playful couples — built around you and your partner.',Visual:VisualWelcome},
{key:'chat',eyebrow:'PRIVATE CHAT',headline:'Your conversation. Just for two.',subtext:'Chat, photos, videos and voice messages in one private space.',Visual:VisualChat},
{key:'vault',eyebrow:'VAULT + BLUR',headline:'Keep the good stuff here.',subtext:'Keep photos and videos together, with Blur when you want a little extra discretion.',Visual:VisualVault},
{key:'burn',eyebrow:'BURN TIMER',headline:'Send it. Burn it. Gone.',subtext:'Put a timer on shared media. When time runs out, Warm Me Up removes it.',Visual:VisualBurn},
{key:'play',eyebrow:'DARE · DICE · WISH',headline:'Keep things playful.',subtext:'Challenge each other, roll the Dice, or drop a Wish whenever the mood strikes.',Visual:VisualPlay},
{key:'stealth',eyebrow:'PRIVACY + STEALTH',headline:'Private when you want it.',subtext:'Blur, discreet alerts and Stealth Mode help keep Warm Me Up from prying eyes.',Visual:VisualStealth},
{key:'finish',eyebrow:'STAY PLAYFUL',headline:'Ready to make it yours?',subtext:'Connect with your partner and start building a space that belongs to just the two of you.',Visual:VisualFinish},];

export default function OnboardingCarousel({mode,onComplete}:Props){
 const insets=useSafeAreaInsets(); const {width,height}=useWindowDimensions(); const isShort=height<760; const flatRef=useRef<FlatList<Slide>>(null); const [currentIndex,setCurrentIndex]=useState(0); const fade=useRef(new Animated.Value(1)).current;
 const viewabilityConfig=useRef({itemVisiblePercentThreshold:55}).current;
 const onViewableItemsChanged=useRef(({viewableItems}:{viewableItems:ViewToken[]})=>{const index=viewableItems[0]?.index;if(typeof index==='number'){setCurrentIndex(index);fade.setValue(.35);Animated.timing(fade,{toValue:1,duration:240,useNativeDriver:true}).start();}}).current;
 const finish=useCallback(()=>onComplete(mode==='preview'?'get-started':'invite-partner'),[mode,onComplete]);
 const handleNext=useCallback(()=>{if(currentIndex<SLIDES.length-1)flatRef.current?.scrollToIndex({index:currentIndex+1,animated:true});else finish();},[currentIndex,finish]);
 const containerPad=useMemo(()=>({paddingTop:Math.max(insets.top,12),paddingBottom:Math.max(insets.bottom,12)}),[insets]);
 return <View style={[styles.root,containerPad]}><LinearGradient colors={['#09090D','#08080B','#050506']} style={StyleSheet.absoluteFill}/><View style={styles.topBar}><View style={styles.brandMini}><WarmupLogo size={24}/><WarmupWordmark size={13}/></View><TouchableOpacity onPress={finish} hitSlop={12} style={styles.skip}><AppText style={styles.skipText}>Skip</AppText></TouchableOpacity></View><FlatList ref={flatRef} data={SLIDES} keyExtractor={item=>item.key} horizontal pagingEnabled showsHorizontalScrollIndicator={false} bounces={false} onViewableItemsChanged={onViewableItemsChanged} viewabilityConfig={viewabilityConfig} renderItem={({item})=>{const Visual=item.Visual;return <View style={[styles.slide,{width}]}><Animated.View style={[styles.slideInner,{opacity:fade,paddingHorizontal:width>=700?Math.max(80,(width-620)/2):24}]}><View style={[styles.visualArea,isShort&&styles.visualAreaShort]}><Visual/></View><View style={styles.copy}><AppText style={styles.eyebrow}>{item.eyebrow}</AppText><AppText style={[styles.headline,isShort&&styles.headlineShort]}>{item.headline}</AppText><AppText style={styles.subtext}>{item.subtext}</AppText></View></Animated.View></View>}}/><View style={styles.footer}><View style={styles.progress}>{SLIDES.map((s,i)=><View key={s.key} style={[styles.progressTrack,i===currentIndex&&styles.progressActive,i<currentIndex&&styles.progressDone]}/>)}</View><TouchableOpacity style={styles.continueButton} onPress={handleNext} activeOpacity={.85}><LinearGradient colors={[ORANGE,ACCENT]} start={{x:0,y:.5}} end={{x:1,y:.5}} style={styles.continueGradient}><AppText style={styles.continueText}>{currentIndex===SLIDES.length-1?(mode==='preview'?'Get Started':'Connect My Partner'):'Continue'}</AppText><ChevronRight size={19} color="#fff"/></LinearGradient></TouchableOpacity></View></View>;
}

const styles=StyleSheet.create({
root:{flex:1,backgroundColor:'#060608'},topBar:{height:48,paddingHorizontal:20,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},brandMini:{flexDirection:'row',alignItems:'center',gap:7,opacity:.82},skip:{paddingHorizontal:8,paddingVertical:8},skipText:{color:'rgba(255,255,255,.58)',fontSize:13,fontFamily:'Inter-SemiBold'},slide:{flex:1},slideInner:{flex:1},visualArea:{flex:1,minHeight:330,justifyContent:'center',paddingTop:8},visualAreaShort:{minHeight:280},copy:{paddingTop:10,paddingBottom:10},eyebrow:{color:ORANGE,fontSize:11,fontFamily:'Inter-Bold',letterSpacing:1.5,marginBottom:9},headline:{color:'#fff',fontSize:32,lineHeight:37,fontFamily:'Inter-Bold',letterSpacing:-.6,maxWidth:520},headlineShort:{fontSize:28,lineHeight:33},subtext:{color:'rgba(255,255,255,.58)',fontSize:15,lineHeight:22,fontFamily:'Inter-Regular',marginTop:10,maxWidth:540},
visualShell:{width:'100%',maxWidth:500,alignSelf:'center',height:'92%',maxHeight:390,minHeight:275,borderRadius:30,borderWidth:1,borderColor:'rgba(255,255,255,.08)',backgroundColor:'#101015',overflow:'hidden',alignItems:'center',justifyContent:'center',padding:22},logoGlow:{position:'absolute',width:210,height:210,borderRadius:105,backgroundColor:'rgba(255,46,138,.09)'},logoRing:{width:142,height:142,borderRadius:71,borderWidth:1,borderColor:'rgba(255,122,61,.24)',backgroundColor:'rgba(255,255,255,.025)',alignItems:'center',justifyContent:'center'},wordmarkWrap:{marginTop:18},twoPill:{marginTop:20,flexDirection:'row',alignItems:'center',gap:7,borderRadius:20,paddingHorizontal:12,paddingVertical:7,backgroundColor:'rgba(255,46,138,.08)',borderWidth:1,borderColor:'rgba(255,46,138,.2)'},twoPillText:{color:'rgba(255,255,255,.66)',fontSize:9,fontFamily:'Inter-Bold',letterSpacing:.7},
miniPhone:{width:'92%',maxWidth:330,borderRadius:24,borderWidth:1,borderColor:'rgba(255,255,255,.11)',backgroundColor:'#0B0B0F',padding:14,gap:9},miniHeader:{flexDirection:'row',alignItems:'center',gap:9,paddingBottom:5},avatar:{width:30,height:30,borderRadius:15,backgroundColor:ACCENT,alignItems:'center',justifyContent:'center'},miniTitle:{color:'#fff',fontSize:12,fontFamily:'Inter-SemiBold'},miniTiny:{color:'rgba(255,255,255,.38)',fontSize:9,fontFamily:'Inter-Regular'},chatBubble:{borderRadius:15,paddingHorizontal:11,paddingVertical:8,maxWidth:'82%'},chatLeft:{alignSelf:'flex-start',backgroundColor:'#1A1A21',borderBottomLeftRadius:4},chatRight:{alignSelf:'flex-end',backgroundColor:'rgba(255,46,138,.2)',borderBottomRightRadius:4},chatText:{color:'rgba(255,255,255,.88)',fontSize:11,fontFamily:'Inter-Regular'},mediaMessage:{alignSelf:'flex-end',width:126,height:72,borderRadius:15,overflow:'hidden'},blurTile:{flex:1,backgroundColor:'#593342',alignItems:'center',justifyContent:'center',gap:3},blurText:{color:'rgba(255,255,255,.75)',fontSize:8,fontFamily:'Inter-SemiBold'},voiceBubble:{flexDirection:'row',alignItems:'center',gap:7,minWidth:155},wave:{flex:1,height:20,flexDirection:'row',alignItems:'center',gap:3},waveBar:{width:2,borderRadius:2,backgroundColor:'rgba(255,122,61,.7)'},voiceTime:{color:'rgba(255,255,255,.4)',fontSize:8},
vaultCard:{width:'92%',maxWidth:330,borderRadius:24,borderWidth:1,borderColor:'rgba(255,255,255,.11)',backgroundColor:'#0B0B0F',padding:14},vaultHeader:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:12},vaultTitle:{color:'#fff',fontSize:18,fontFamily:'Inter-Bold'},grid:{flexDirection:'row',flexWrap:'wrap',gap:7},gridTile:{width:'48%',height:82,borderRadius:13,alignItems:'center',justifyContent:'center'},gridBlur:{backgroundColor:'#4A303B',gap:3},featureStrip:{marginTop:11,flexDirection:'row',alignItems:'center',gap:7,backgroundColor:'rgba(255,122,61,.07)',borderRadius:10,padding:8},featureStripText:{color:'rgba(255,255,255,.52)',fontSize:9,fontFamily:'Inter-SemiBold'},
burnMedia:{width:210,height:120,borderRadius:18,backgroundColor:'#34232A',alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:'rgba(255,255,255,.08)'},burnBadge:{position:'absolute',top:9,right:9,flexDirection:'row',alignItems:'center',gap:4,backgroundColor:'rgba(255,46,138,.78)',paddingHorizontal:7,paddingVertical:4,borderRadius:9},burnBadgeText:{color:'#fff',fontSize:8,fontFamily:'Inter-Bold',letterSpacing:.5},timerWrap:{width:110,height:110,marginTop:-28,alignItems:'center',justifyContent:'center'},timerSegments:{position:'absolute',width:110,height:110,alignItems:'center',justifyContent:'center'},segment:{position:'absolute',width:3,height:9,borderRadius:2,backgroundColor:ACCENT},timerCenter:{width:80,height:80,borderRadius:40,backgroundColor:'#111116',alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:'rgba(255,255,255,.08)'},timerText:{color:'#fff',fontSize:18,fontFamily:'Inter-Bold'},timerLabel:{color:'rgba(255,255,255,.35)',fontSize:7,fontFamily:'Inter-Bold',letterSpacing:1},microCopy:{color:'rgba(255,255,255,.43)',fontSize:10,fontFamily:'Inter-Regular',marginTop:2},
playStack:{width:'92%',maxWidth:340,gap:10},playCard:{minHeight:68,borderRadius:18,borderWidth:1,borderColor:'rgba(255,255,255,.09)',backgroundColor:'#17171D',flexDirection:'row',alignItems:'center',gap:11,padding:11},playHero:{backgroundColor:'rgba(255,46,138,.08)',borderColor:'rgba(255,46,138,.25)',transform:[{scale:1.04}]},playIcon:{width:42,height:42,borderRadius:13,backgroundColor:'rgba(255,122,61,.1)',alignItems:'center',justifyContent:'center'},playCopy:{flex:1},playTitle:{color:'#fff',fontSize:14,fontFamily:'Inter-Bold'},playSub:{color:'rgba(255,255,255,.42)',fontSize:10,fontFamily:'Inter-Regular',marginTop:2},livePill:{backgroundColor:ACCENT,borderRadius:9,paddingHorizontal:7,paddingVertical:4},livePillText:{color:'#fff',fontSize:7,fontFamily:'Inter-Bold',letterSpacing:.6},
weatherCard:{width:210,height:160,borderRadius:24,backgroundColor:'#142B45',borderWidth:1,borderColor:'rgba(255,255,255,.13)',padding:16,justifyContent:'space-between'},weatherTop:{alignItems:'center'},weatherCity:{color:'#fff',fontSize:16,fontFamily:'Inter-SemiBold'},weatherTiny:{color:'rgba(255,255,255,.68)',fontSize:9,fontFamily:'Inter-Regular'},weatherMain:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:18},weatherTemp:{color:'#fff',fontSize:44,fontFamily:'Inter-Regular'},weatherSun:{width:35,height:35,borderRadius:18,backgroundColor:'#FFD26A'},weatherLine:{alignItems:'center'},stealthBadge:{width:'92%',maxWidth:330,marginTop:-12,borderRadius:16,backgroundColor:'#17171E',borderWidth:1,borderColor:'rgba(255,46,138,.22)',padding:11,flexDirection:'row',alignItems:'center',gap:10},stealthTitle:{color:'#fff',fontSize:11,fontFamily:'Inter-Bold'},stealthSub:{color:'rgba(255,255,255,.43)',fontSize:8,lineHeight:12,fontFamily:'Inter-Regular',marginTop:2},privacyRow:{marginTop:13,flexDirection:'row',alignItems:'center',gap:5},privacyText:{color:'rgba(255,255,255,.45)',fontSize:8,fontFamily:'Inter-SemiBold'},dot:{width:3,height:3,borderRadius:2,backgroundColor:'rgba(255,255,255,.18)',marginHorizontal:2},
finishHearts:{flexDirection:'row',alignItems:'center'},personCircle:{width:82,height:82,borderRadius:41,alignItems:'center',justifyContent:'center',borderWidth:1.5},personA:{backgroundColor:'rgba(255,122,61,.12)',borderColor:'rgba(255,122,61,.4)'},personB:{backgroundColor:'rgba(255,46,138,.14)',borderColor:'rgba(255,46,138,.45)'},personInitial:{color:ORANGE,fontSize:12,fontFamily:'Inter-Bold',letterSpacing:.7},connection:{width:92,height:44,justifyContent:'center',alignItems:'center'},connectionLine:{position:'absolute',width:'100%',height:2},heartNode:{width:42,height:42,borderRadius:21,backgroundColor:ACCENT,alignItems:'center',justifyContent:'center',borderWidth:4,borderColor:'#101015'},inviteCard:{width:'92%',maxWidth:340,marginTop:30,borderRadius:18,backgroundColor:'rgba(255,255,255,.045)',borderWidth:1,borderColor:'rgba(255,255,255,.09)',padding:13,flexDirection:'row',alignItems:'center',gap:11},inviteTitle:{color:'#fff',fontSize:12,fontFamily:'Inter-Bold'},inviteSub:{color:'rgba(255,255,255,.44)',fontSize:9,lineHeight:13,fontFamily:'Inter-Regular',marginTop:2},
footer:{paddingHorizontal:24,paddingTop:10},progress:{flexDirection:'row',gap:5,alignItems:'center',justifyContent:'center',marginBottom:13},progressTrack:{height:3,width:22,borderRadius:2,backgroundColor:'rgba(255,255,255,.12)'},progressActive:{width:34,backgroundColor:ACCENT},progressDone:{backgroundColor:'rgba(255,122,61,.45)'},continueButton:{width:'100%',maxWidth:560,alignSelf:'center',borderRadius:16,overflow:'hidden'},continueGradient:{minHeight:52,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7,paddingHorizontal:18},continueText:{color:'#fff',fontSize:15,fontFamily:'Inter-Bold'},
});