-- Ensure video items created by Chat auto-save resolve the deterministic poster frame
-- generated by uploadMediaFile, even when older client code omits blurred_thumbnail_path.
CREATE OR REPLACE FUNCTION public.set_vault_video_thumbnail_path()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF NEW.media_type = 'video'
     AND NEW.blurred_thumbnail_path IS NULL
     AND COALESCE(NEW.storage_path, NEW.file_path) IS NOT NULL THEN
    NEW.blurred_thumbnail_path := regexp_replace(
      COALESCE(NEW.storage_path, NEW.file_path),
      '\.[^.]+$',
      '_thumb.jpg'
    );
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_vault_video_thumbnail_path_before_write ON public.vault_items;
CREATE TRIGGER set_vault_video_thumbnail_path_before_write
BEFORE INSERT OR UPDATE OF storage_path, file_path, media_type, blurred_thumbnail_path
ON public.vault_items
FOR EACH ROW
EXECUTE FUNCTION public.set_vault_video_thumbnail_path();